services:
  web:
    image: ghcr.io/minyic7/majiang-web:latest
    ports:
      - "3002:80"
    depends_on:
      - server
    restart: unless-stopped

  server:
    image: ghcr.io/minyic7/majiang-server:latest
    ports:
      - "7702:7702"
    environment:
      - PORT=7702
    restart: unless-stopped
